### ISSUE TITLE
Proposal types Alliance, Campaign, Hypha

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#24]
## 3 Types of Proposals

* Campaigns - Seeds for campaigns that will get their own website where people can request rewards for submitting contributions, and verifiers verify that tasks have been done.
* Alliances - Seeds that are passed go to their escrow account
* Hypha - reciepient can only by Seeds.hypha

### Campaigns

* **Liquid Seeds from gift.seeds**
* Campaigns are managed by Hypha initially
* Campaign funds go into campaign accounts which will have multi sig for our verifiers (1/3) so everyone can verify tasks have been done and release funds
* We can create a campaign fund account when the campaign has passed - it could be managed by a special seeds account before handing over control to ambassadors? 
* Not sure this can be automated. The stewards might have to do this.

### Alliances 
* **Escrow Seeds from allies.seeds**
* we send the Seeds to the escrow account with the org as the beneficiary. 
* org needs to be the proposer

### Hypha
* **Liquid Seeds from milest.seeds**
* When we request from milest.seeds account, it can only go to seeds.hypha
* I think we can soft enforce this on the app level though? 
* If random people request from this account... we vote no?!

## Tasks

- [x] Enforce campaign type by funding wallet
- [x] Add permissions for all funding wallets
- [x] Put allies funds into escrow rather than directly transferring
- [x] Add permission for vesting contract access so we can escrow funds
- [x] Add unit test for escrow funds
- [x] Add unit test for milest.seeds
- [x] Add unit test for funding with allies.seeds

actcam.seeds (can we create this account as a catchall for campaigns?) It's going to be the standard account that if they forget to put in a campaign receiving address it goes here.

**Comment by n13** [comment]
Alliance  change: 
- deploy accounts, proposals, escrow
- updatePermissions
